name: Build and Deploy to Vercel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      - name: Build project with Kobweb
        run: ./gradlew :site:kobwebExport --no-daemon
        
      - name: Prepare deployment files
        run: |
          # Copy main page as index.html
          cp site/.kobweb/site/pages/index.html site/.kobweb/site/index.html
          # Create simple vercel.json
          echo '{"version": 2}' > site/.kobweb/site/vercel.json
          # List files for debugging
          ls -la site/.kobweb/site/
          
      - name: Install Vercel CLI
        run: npm install -g vercel@latest
        
      - name: Deploy to Vercel (Production)
        if: github.ref == 'refs/heads/main'
        run: |
          vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --yes --cwd site/.kobweb/site
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          
      - name: Deploy to Vercel (Preview)
        if: github.event_name == 'pull_request'
        run: |
          vercel --token ${{ secrets.VERCEL_TOKEN }} --yes --cwd site/.kobweb/site
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}